create sequence hibernate_sequence start with 1 increment by 1;
create table exchange_rates_request (id bigint generated by default as identity, code integer, currency varchar(255), table_name varchar(255), primary key (id));
create table rate_request (id bigint not null, ask float not null, bid float not null, effective_date timestamp, no varchar(255), exchange_id bigint, primary key (id));
alter table rate_request add constraint FKa5u8744k8cjxuxeoikjnq50n9 foreign key (exchange_id) references exchange_rates_request;

-- Insert example
insert into rate_request (ask, bid, effective_date, exchange_id, no, id) values (?, ?, ?, ?, ?, ?);

-- Select example
select exchangera0_.id as id1_0_0_, exchangera0_.code as code2_0_0_, exchangera0_.currency as currency3_0_0_, exchangera0_.table_name as table_na4_0_0_ from exchange_rates_request exchangera0_ where exchangera0_.id=?;

--Update example
update rate_request set ask=?, bid=?, effective_date=?, exchange_id=?, no=? where id=?;