//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.13 at 07:23:00 PM CEST 
//


package pl.com.khryniewicki.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Rates complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Rates"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BestBidRate" type="{http://response.khryniewicki.com.pl}BestBidRate"/&gt;
 *         &lt;element name="BestAskRate" type="{http://response.khryniewicki.com.pl}BestAskRate"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Rates", propOrder = {
    "bestBidRate",
    "bestAskRate"
})
public class Rates {

    @XmlElement(name = "BestBidRate", required = true)
    protected BestBidRate bestBidRate;
    @XmlElement(name = "BestAskRate", required = true)
    protected BestAskRate bestAskRate;

    /**
     * Gets the value of the bestBidRate property.
     * 
     * @return
     *     possible object is
     *     {@link BestBidRate }
     *     
     */
    public BestBidRate getBestBidRate() {
        return bestBidRate;
    }

    /**
     * Sets the value of the bestBidRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BestBidRate }
     *     
     */
    public void setBestBidRate(BestBidRate value) {
        this.bestBidRate = value;
    }

    /**
     * Gets the value of the bestAskRate property.
     * 
     * @return
     *     possible object is
     *     {@link BestAskRate }
     *     
     */
    public BestAskRate getBestAskRate() {
        return bestAskRate;
    }

    /**
     * Sets the value of the bestAskRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BestAskRate }
     *     
     */
    public void setBestAskRate(BestAskRate value) {
        this.bestAskRate = value;
    }

}
