//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.16 at 01:01:29 AM CEST 
//


package pl.com.khryniewicki.dto.response;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="StartingDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="EndingDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "currency",
        "startingDate",
        "endingDate"
})
@XmlRootElement(name = "getCurrencyRequest")
public class GetCurrencyRequest {

    @XmlElement(name = "Currency", required = true)
    protected String currency;
    @XmlElement(name = "StartingDate", required = true)
    protected String startingDate;
    @XmlElement(name = "EndingDate", required = true)
    protected String endingDate;

    /**
     * Gets the value of the currency property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the startingDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStartingDate() {
        return startingDate;
    }

    /**
     * Sets the value of the startingDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStartingDate(String value) {
        this.startingDate = value;
    }

    /**
     * Gets the value of the endingDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEndingDate() {
        return endingDate;
    }

    /**
     * Sets the value of the endingDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEndingDate(String value) {
        this.endingDate = value;
    }

}
