//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.16 at 05:29:49 AM CEST 
//


package pl.com.khryniewicki.dto.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Rates complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Rates"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="HighestBidRate" type="{http://response.dto.khryniewicki.com.pl}HighestBidRate"/&gt;
 *         &lt;element name="LowestAskRate" type="{http://response.dto.khryniewicki.com.pl}LowestAskRate"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Rates", propOrder = {
    "highestBidRate",
    "lowestAskRate"
})
public class Rates {

    @XmlElement(name = "HighestBidRate", required = true)
    protected HighestBidRate highestBidRate;
    @XmlElement(name = "LowestAskRate", required = true)
    protected LowestAskRate lowestAskRate;

    /**
     * Gets the value of the highestBidRate property.
     * 
     * @return
     *     possible object is
     *     {@link HighestBidRate }
     *     
     */
    public HighestBidRate getHighestBidRate() {
        return highestBidRate;
    }

    /**
     * Sets the value of the highestBidRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link HighestBidRate }
     *     
     */
    public void setHighestBidRate(HighestBidRate value) {
        this.highestBidRate = value;
    }

    /**
     * Gets the value of the lowestAskRate property.
     * 
     * @return
     *     possible object is
     *     {@link LowestAskRate }
     *     
     */
    public LowestAskRate getLowestAskRate() {
        return lowestAskRate;
    }

    /**
     * Sets the value of the lowestAskRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link LowestAskRate }
     *     
     */
    public void setLowestAskRate(LowestAskRate value) {
        this.lowestAskRate = value;
    }

}
