//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.12 at 10:43:19 PM CEST 
//


package pl.com.khryniewicki.request;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ExchangeRatesSeries" type="{http://www.w3.org/2001/XMLSchema-instance}ExchangeRatesSeries"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "exchangeRatesSeries"
})
@XmlRootElement(name = "getCurrencyResponse")
public class GetCurrencyResponse {

    @XmlElement(name = "ExchangeRatesSeries", required = true)
    protected pl.com.khryniewicki.request.ExchangeRatesSeries exchangeRatesSeries;

    /**
     * Gets the value of the exchangeRatesSeries property.
     * 
     * @return
     *     possible object is
     *     {@link pl.com.khryniewicki.request.ExchangeRatesSeries }
     *     
     */
    public pl.com.khryniewicki.request.ExchangeRatesSeries getExchangeRatesSeries() {
        return exchangeRatesSeries;
    }

    /**
     * Sets the value of the exchangeRatesSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link pl.com.khryniewicki.request.ExchangeRatesSeries }
     *     
     */
    public void setExchangeRatesSeries(pl.com.khryniewicki.request.ExchangeRatesSeries value) {
        this.exchangeRatesSeries = value;
    }

}
