//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.12 at 10:43:19 PM CEST 
//


package pl.com.khryniewicki.request;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.w3._2001.xmlschema_instance package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.w3._2001.xmlschema_instance
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link pl.com.khryniewicki.request.GetCurrencyRequest }
     * 
     */
    public pl.com.khryniewicki.request.GetCurrencyRequest createGetCurrencyRequest() {
        return new pl.com.khryniewicki.request.GetCurrencyRequest();
    }

    /**
     * Create an instance of {@link GetCurrencyResponse }
     * 
     */
    public GetCurrencyResponse createGetCurrencyResponse() {
        return new GetCurrencyResponse();
    }

    /**
     * Create an instance of {@link ExchangeRatesSeries }
     * 
     */
    public ExchangeRatesSeries createExchangeRatesSeries() {
        return new ExchangeRatesSeries();
    }

    /**
     * Create an instance of {@link pl.com.khryniewicki.request.Rate }
     * 
     */
    public pl.com.khryniewicki.request.Rate createRate() {
        return new pl.com.khryniewicki.request.Rate();
    }

}
