//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.12 at 10:43:19 PM CEST 
//


package pl.com.khryniewicki.dto.request;


import javax.persistence.*;
import javax.xml.bind.annotation.*;

import java.util.GregorianCalendar;


/**
 * <p>Java class for Rate complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Rate"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="No" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="EffectiveDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Bid" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="Ask" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Rate", propOrder = {
        "id",
        "no",
        "effectiveDate",
        "bid",
        "ask",
        "exchange"
})
@XmlRootElement(name = "Rate")
@Entity
public class RateRequest  {
    @Id
    @GeneratedValue()
    @XmlElement(name = "id", required = true)
    protected Long id;
    @XmlElement(name = "No", required = true)
    protected String no;
    @XmlElement(name = "EffectiveDate", required = true)
    protected GregorianCalendar effectiveDate;
    @XmlElement(name = "Bid", required = true)
    protected float bid;
    @XmlElement(name = "Ask", required = true)
    protected float ask;
    @XmlElement(name = "Exchange", required = true)
    @ManyToOne(fetch = FetchType.EAGER)
    protected ExchangeRatesRequest exchange;

    public ExchangeRatesRequest getExchange() {
        return exchange;
    }

    public void setExchange(ExchangeRatesRequest exchange) {
        this.exchange = exchange;
    }

    /**
     * Gets the value of the no property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNo() {
        return no;
    }

    /**
     * Sets the value of the no property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNo(String value) {
        this.no = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public GregorianCalendar getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEffectiveDate(GregorianCalendar value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the bid property.
     */
    public float getBid() {
        return bid;
    }

    /**
     * Sets the value of the bid property.
     */
    public void setBid(float value) {
        this.bid = value;
    }

    /**
     * Gets the value of the ask property.
     */
    public float getAsk() {
        return ask;
    }

    /**
     * Sets the value of the ask property.
     */
    public void setAsk(float value) {
        this.ask = value;
    }

    @Override
    public String toString() {
        return "Rate{" +
                "no='" + no + '\'' +
                ", effectiveDate='" + effectiveDate + '\'' +
                ", bid=" + bid +
                ", ask=" + ask +
                '}';
    }
}
